### ISSUE TITLE
Minimum Values

### ISSUE THREAD

**Issue by ByronThompson** [jab0073/CS-499-Statistical-Analyzer#14]
Certain Measures (Namely: Correlation Coefficient and Spearmen Rank) produce errors when attempting to evaluate on too small of data sets (Measures tested with DataSets consisting of 2 samples of one value each). Additionally, Least Square Line produces NaN in the same circumstances, advise same as #12

**Comment by ByronThompson** [comment]
Error Produced by Correlation Coefficient
![image](https://user-images.githubusercontent.com/29874212/195930659-052aaba5-152c-422f-b1d2-8eaa6fa87949.png)

**Comment by jab0073** [comment]
would something like this in the validate function for the Correlation Coefficient and Spearmen Rank seem to alleviate this issue?

<img width="629" alt="image" src="https://user-images.githubusercontent.com/93546944/195964095-9bc02c33-b8db-4421-ae65-7aaa4fb6baf4.png">
